services:
  server:
    build: PhoneBook2
    image: phonebook2-server
    container_name: phonebook2-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/phonebook2

      - SPRING_DATASOURCE_USERNAME=phonebook2

      - SPRING_DATASOURCE_PASSWORD=phonebook2


  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=phonebook2
      - POSTGRES_USER=phonebook2
      - POSTGRES_DB=phonebook2

    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10